### ISSUE TITLE
Create a new brand identity

### ISSUE THREAD

**Issue by johnpeart** [johnpeart/lgbt-councillors#1]
The current website uses recycled branding from the [LGBT+ Members of Parliament](https://mps.whoare.lgbt) dataset.

Local authorities don't have a single identifier like the Parliament portcullis, so a new, different brand image will be required.

**Comment by maxxturing** [comment]
Will have a think...

Suggestion: a rainbow-coloured [rosette](https://www.local.gov.uk/rosettes).

**Comment by johnpeart** [comment]
![Councillors Who Are LGBT](https://user-images.githubusercontent.com/4903081/153958422-775651a3-f404-49f2-9ea8-2df13ba07724.png)

How about something like this?

**Comment by maxxturing** [comment]
@johnpeart looks fab!

**Comment by johnpeart** [comment]
Site now updated with this motif throughout...
