### ISSUE TITLE
Identities are displaying as LGBT+ instead of recorded identities

### ISSUE THREAD

**Issue by maxxturing** [johnpeart/lgbt-councillors#3]
Identities of councillors are displaying as LGBT+ instead of the identity listed in the [csv database](https://github.com/johnpeart/lgbt-councillors/blob/main/_data/councillors.csv)

<img width="804" alt="Screenshot 2022-03-22 at 15 51 41" src="https://user-images.githubusercontent.com/36308251/159522789-7320c88f-1414-4dbc-80ca-629f9585556c.png">

Is this a bug 🐛  or an intentional design decision?

**Comment by johnpeart** [comment]
It's a bug that has now been fixed by commit 4538fdf7273616071a8aa12e267bfae73fb09cb0.
